import HomeLayout from '@/components/templates/home/layout'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Home - Dashboard',
  description: 'Generated by create next app',
};
export default function Home() {
    return (
      <HomeLayout>
        <section className='row'>
          <div className="col-6"></div>
          <div className="col-6"></div>
        </section>
      </HomeLayout>
    )
}