import HomeHeader from '@/components/organisms/HomeHeader';
import Footer from '@/components/organisms/Footer';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Home - Dashboard',
  description: 'Generated by create next app',
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
